### ISSUE TITLE
Not a good idea for ultrasonic sensor

### ISSUE THREAD

**Issue by glmnet** [mhaack/home-assistant-config#83]
How well is it working. The esphome one. I see you define the sensor three times doing different calculations. Since that makes sense on the calculation side I don’t know if the thing might be confused. 
I really don’t know the Internals of the sensor, it might be ok but it might be wrong. E.g if using interrupts then you may send two triggers and receive one echo etc. 

Ideally you’ll create only one ultrasonic sensor then two additional sensors. On the value received of the ultrasonic you can do additional calculations and update the other two (template) sensors

**Comment by mhaack** [comment]
Thanks for the pointer to the template sensors. Actually I got accurate numbers with the initial approach. But I changed to only one ultrasonic sensor, think that is the better solution.
